-- Adminer 4.3.1 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `reviews`;
CREATE TABLE `reviews` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(16) NOT NULL,
  `note` text NOT NULL,
  `date` date DEFAULT NULL,
  `ip` int(11) unsigned DEFAULT NULL,
  `likes` int(8) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `reviews` (`id`, `name`, `note`, `date`, `ip`, `likes`) VALUES
(1,	'Дмитрий',	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra fringilla enim, a molestie magna sagittis ac. Aliquam erat volutpat. Aliquam eu tellus facilisis, venenatis mauris nec, pharetra ante. Sed pretium lacus eget dui pulvinar feugiat. Cras suscipit et odio non elementum. Integer turpis quam, pellentesque et est ut, dapibus feugiat eros. Suspendisse scelerisque nibh at justo molestie, a facilisis leo faucibus. Suspendisse tempus, lacus a tempus consectetur, leo enim ultricies sapien, ut porttitor urna ex a ante. Aenean tristique tempus elit, eget vehicula nulla ultrices quis. Suspendisse vehicula cursus aliquet. Praesent nibh enim, eleifend ac fermentum vitae, vehicula quis ante. Nulla accumsan, justo non eleifend hendrerit, enim diam scelerisque turpis, et eleifend tellus velit nec libero. Integer et dictum nisi. Curabitur turpis metus, viverra non nunc et, viverra lacinia magna.\r\n\r\nMaecenas sodales ullamcorper mi et finibus. Sed ut commodo augue. Etiam feugiat felis a congue consequat. Nunc sodales tincidunt elit ullamcorper cursus. Aliquam tempus hendrerit porttitor. Morbi ac facilisis turpis, eu ultricies odio. Proin nisl ex, fringilla id nisi ac, placerat vehicula felis. Mauris ut venenatis tellus. Etiam rutrum vehicula ante, vitae eleifend ante convallis eget. Phasellus consequat posuere tellus, vel suscipit nunc fringilla vel.\r\n\r\nMorbi scelerisque laoreet magna, a imperdiet dui vehicula vel. Vestibulum consequat, nibh eget tempus efficitur, sem velit pellentesque felis, a consequat orci leo nec velit. Aenean tortor neque, vestibulum ut commodo ut, volutpat id orci. Sed vitae dui condimentum, tincidunt metus a, sollicitudin eros. Sed a augue nec justo feugiat malesuada non ac odio. In quis commodo purus. Proin lacinia diam in augue laoreet malesuada sed vitae quam.',	'2017-10-05',	2130706433,	16),
(2,	'Егор',	'Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, obcaecati cupiditate non provident, similique sunt in culpa, qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.\r\n\r\nQuis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, obcaecati cupiditate non provident, similique sunt in culpa, qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',	'2017-10-06',	2130706433,	3),
(3,	'Аркадий',	'Сайт рыбатекст поможет дизайнеру, верстальщику, вебмастеру сгенерировать несколько абзацев более менее осмысленного текста рыбы на русском языке, а начинающему оратору отточить навык публичных выступлений в домашних условиях. При создании генератора мы использовали небезизвестный универсальный код речей. Текст генерируется абзацами случайным образом от двух до десяти предложений в абзаце, что позволяет сделать текст более привлекательным и живым для визуально-слухового восприятия.\r\n\r\nПо своей сути рыбатекст является альтернативой традиционному lorem ipsum, который вызывает у некторых людей недоумение при попытках прочитать рыбу текст. В отличии от lorem ipsum, текст рыба на русском языке наполнит любой макет непонятным смыслом и придаст неповторимый колорит советских времен.',	'2017-10-09',	2130706433,	5),
(16,	'Константин',	'Таким образом новая модель организационной деятельности позволяет выполнять важные задания по разработке систем массового участия. Таким образом сложившаяся структура организации способствует подготовки и реализации форм развития.\r\n\r\nЗначимость этих проблем настолько очевидна, что сложившаяся структура организации позволяет выполнять важные задания по разработке соответствующий условий активизации. Товарищи! дальнейшее развитие различных форм деятельности способствует подготовки и реализации существенных финансовых и административных условий. Идейные соображения высшего порядка, а также сложившаяся структура организации играет важную роль в формировании направлений прогрессивного развития. Товарищи! сложившаяся структура организации позволяет выполнять важные задания по разработке существенных финансовых и административных условий.',	'2017-10-10',	2130706433,	1);

-- 2017-10-10 07:31:56
